apiVersion: apps/v1
kind: Deployment
metadata:
  name: rd-hawks
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rd-hawks
  template:
    metadata:
      labels:
        app: rd-hawks
    spec:
      containers:
      - image: jyidiego/riverdell-hawks:latest
        name: rd-hawks
        ports:
        - containerPort: 8080