service:
  name: riverdell-hawks
  identifier: riverdellhawks
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: rdhawks
            type: Kustomize
            spec:
              store:
                type: Github
                spec:
                  connectorRef: account.Github
                  gitFetchType: Branch
                  folderPath: kustomize
                  repoName: jyidiego/riverdell-hawks
                  branch: main
              pluginPath: ""
              skipResourceVersioning: false
              enableDeclarativeRollback: false
    type: Kubernetes
